# Generated by Django 2.0.8 on 2024-02-29 05:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingPageAllowedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_descendants",
                    models.BooleanField(
                        default=False,
                        help_text="Check this box to make the decsendants of the selected page visible as well.",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Select a page whose content should be visible, even when the holding page is activated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HoldingPageSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holdingpage_active",
                    models.BooleanField(default=False, help_text="Enable holding page"),
                ),
                (
                    "allow_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Allow staff to access the site, even with holding page enadled",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="holdingpageallowedpage",
            name="settings",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allowed_pages",
                to="wagtail_holdingpage.HoldingPageSettings",
            ),
        ),
    ]
